# Site settings
title: The Nasty AI Blog 
author:
  name: Mohamed M.I
  email: mohamedinasmohamed1998@domain.com
description: "Why are you reading this. But whyy. Never Mind this is my blog on my data annalytics , AI and ML projects"

# Build settings
remote_theme: jekyll/minima
